services:
  web:
    build: apache
    ports:
      - 80:80
    volumes:
      - ./apache/tarefa1.conf:/etc/apache2/sites-enabled/tarefa1.conf
      - ./david.lan:/opt/web/david.lan

    networks:
      redeapache:
        aliases:
          - david.lan
          - eq1.david.lan
    develop:
      watch:
        - path: ./apache/test1.conf
          action: restart

  cliente:
    image: brunosct/debian12-cliente-firefox
    hostname: cliente
    networks:
      - redeapache
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  redeapache: